=== AbiWord/abiword/plugins/mathview/data/entities-table.dtd
<?xml version="1.0" encoding="iso8859-1"?>
<!ELEMENT entities-table (entity)*>

<!ELEMENT entity EMPTY>
<!ATTLIST entity
  name  CDATA #REQUIRED
  value CDATA #REQUIRED
>

=== AbiWord/abiword/plugins/mathview/data/entities-table.xml
<?xml version="1.0"?>
<!DOCTYPE entities-table SYSTEM "entities-table.dtd">

<entities-table>
  <entity name="Aacute" value="&#x000C1;"/>
  <entity name="aacute" value="&#x000E1;"/>
  <entity name="Abreve" value="&#x00102;"/>
  <entity name="abreve" value="&#x00103;"/>
  <entity name="ac" value="&#x0223E;"/>
  <entity name="acd" value="&#x0223F;"/>
  <entity name="acE" value="&#x0223E;&#x00333;"/>
  <entity name="Acirc" value="&#x000C2;"/>
  <entity name="acirc" value="&#x000E2;"/>
  <entity name="acute" value="&#x000B4;"/>
  <entity name="Acy" value="&#x00410;"/>
  <entity name="acy" value="&#x00430;"/>
  <entity name="AElig" value="&#x000C6;"/>
  <entity name="aelig" value="&#x000E6;"/>
  <entity name="af" value="&#x02061;"/>
  <entity name="Afr" value="&#x1D504;"/>
  <entity name="afr" value="&#x1D51E;"/>
  <entity name="Agrave" value="&#x000C0;"/>
  <entity name="agrave" value="&#x000E0;"/>
  <entity name="aleph" value="&#x02135;"/>
  <entity name="alpha" value="&#x003B1;"/>
  <entity name="Amacr" value="&#x00100;"/>
  <entity name="amacr" value="&#x00101;"/>
  <entity name="amalg" value="&#x02A3F;"/>
  <entity name="amp" value="&#x00026;"/>
  <entity name="And" value="&#x02A53;"/>
  <entity name="and" value="&#x02227;"/>
  <entity name="andand" value="&#x02A55;"/>
  <entity name="andd" value="&#x02A5C;"/>
  <entity name="andslope" value="&#x02A58;"/>
  <entity name="andv" value="&#x02A5A;"/>
  <entity name="ang" value="&#x02220;"/>
  <entity name="ange" value="&#x029A4;"/>
  <entity name="angle" value="&#x02220;"/>
  <entity name="angmsd" value="&#x02221;"/>
  <entity name="angmsdaa" value="&#x029A8;"/>
  <entity name="angmsdab" value="&#x029A9;"/>
  <entity name="angmsdac" value="&#x029AA;"/>
  <entity name="angmsdad" value="&#x029AB;"/>
  <entity name="angmsdae" value="&#x029AC;"/>
  <entity name="angmsdaf" value="&#x029AD;"/>
  <entity name="angmsdag" value="&#x029AE;"/>
  <entity name="angmsdah" value="&#x029AF;"/>
  <entity name="angrt" value="&#x0221F;"/>
  <entity name="angrtvb" value="&#x022BE;"/>
  <entity name="angrtvbd" value="&#x0299D;"/>
  <entity name="angsph" value="&#x02222;"/>
  <entity name="angst" value="&#x0212B;"/>
  <entity name="angzarr" value="&#x0237C;"/>
  <entity name="Aogon" value="&#x00104;"/>
  <entity name="aogon" value="&#x00105;"/>
  <entity name="Aopf" value="&#x1D538;"/>
  <entity name="aopf" value="&#x1D552;"/>
  <entity name="ap" value="&#x02248;"/>
  <entity name="apacir" value="&#x02A6F;"/>
  <entity name="apE" value="&#x02A70;"/>
  <entity name="ape" value="&#x0224A;"/>
  <entity name="apid" value="&#x0224B;"/>
  <entity name="apos" value="&#x00027;"/>
  <entity name="ApplyFunction" value="&#x02061;"/>
  <entity name="approx" value="&#x02248;"/>
  <entity name="approxeq" value="&#x0224A;"/>
  <entity name="Aring" value="&#x000C5;"/>
  <entity name="aring" value="&#x000E5;"/>
  <entity name="Ascr" value="&#x1D49C;"/>
  <entity name="ascr" value="&#x1D4B6;"/>
  <entity name="Assign" value="&#x02254;"/>
  <entity name="ast" value="&#x0002A;"/>
  <entity name="asymp" value="&#x02248;"/>
  <entity name="asympeq" value="&#x0224D;"/>
  <entity name="Atilde" value="&#x000C3;"/>
  <entity name="atilde" value="&#x000E3;"/>
  <entity name="Auml" value="&#x000C4;"/>
  <entity name="auml" value="&#x000E4;"/>
  <entity name="awconint" value="&#x02233;"/>
  <entity name="awint" value="&#x02A11;"/>
  <entity name="backcong" value="&#x0224C;"/>
  <entity name="backepsilon" value="&#x003F6;"/>
  <entity name="backprime" value="&#x02035;"/>
  <entity name="backsim" value="&#x0223D;"/>
  <entity name="backsimeq" value="&#x022CD;"/>
  <entity name="Backslash" value="&#x02216;"/>
  <entity name="Barv" value="&#x02AE7;"/>
  <entity name="barvee" value="&#x022BD;"/>
  <entity name="Barwed" value="&#x02306;"/>
  <entity name="barwed" value="&#x02305;"/>
  <entity name="barwedge" value="&#x02305;"/>
  <entity name="bbrk" value="&#x023B5;"/>
  <entity name="bbrktbrk" value="&#x023B6;"/>
  <entity name="bcong" value="&#x0224C;"/>
  <entity name="Bcy" value="&#x00411;"/>
  <entity name="bcy" value="&#x00431;"/>
  <entity name="becaus" value="&#x02235;"/>
  <entity name="Because" value="&#x02235;"/>
  <entity name="because" value="&#x02235;"/>
  <entity name="bemptyv" value="&#x029B0;"/>
  <entity name="bepsi" value="&#x003F6;"/>
  <entity name="bernou" value="&#x0212C;"/>
  <entity name="Bernoullis" value="&#x0212C;"/>
  <entity name="beta" value="&#x003B2;"/>
  <entity name="beth" value="&#x02136;"/>
  <entity name="between" value="&#x0226C;"/>
  <entity name="Bfr" value="&#x1D505;"/>
  <entity name="bfr" value="&#x1D51F;"/>
  <entity name="bigcap" value="&#x022C2;"/>
  <entity name="bigcirc" value="&#x025EF;"/>
  <entity name="bigcup" value="&#x022C3;"/>
  <entity name="bigodot" value="&#x02A00;"/>
  <entity name="bigoplus" value="&#x02A01;"/>
  <entity name="bigotimes" value="&#x02A02;"/>
  <entity name="bigsqcup" value="&#x02A06;"/>
  <entity name="bigstar" value="&#x02605;"/>
  <entity name="bigtriangledown" value="&#x025BD;"/>
  <entity name="bigtriangleup" value="&#x025B3;"/>
  <entity name="biguplus" value="&#x02A04;"/>
  <entity name="bigvee" value="&#x022C1;"/>
  <entity name="bigwedge" value="&#x022C0;"/>
  <entity name="bkarow" value="&#x0290D;"/>
  <entity name="blacklozenge" value="&#x029EB;"/>
  <entity name="blacksquare" value="&#x025AA;"/>
  <entity name="blacktriangle" value="&#x025B4;"/>
  <entity name="blacktriangledown" value="&#x025BE;"/>
  <entity name="blacktriangleleft" value="&#x025C2;"/>
  <entity name="blacktriangleright" value="&#x025B8;"/>
  <entity name="blank" value="&#x02423;"/>
  <entity name="blk12" value="&#x02592;"/>
  <entity name="blk14" value="&#x02591;"/>
  <entity name="blk34" value="&#x02593;"/>
  <entity name="block" value="&#x02588;"/>
  <entity name="bne" value="&#x0003D;&#x020E5;"/>
  <entity name="bnequiv" value="&#x02261;&#x020E5;"/>
  <entity name="bNot" value="&#x02AED;"/>
  <entity name="bnot" value="&#x02310;"/>
  <entity name="Bopf" value="&#x1D539;"/>
  <entity name="bopf" value="&#x1D553;"/>
  <entity name="bot" value="&#x022A5;"/>
  <entity name="bottom" value="&#x022A5;"/>
  <entity name="bowtie" value="&#x022C8;"/>
  <entity name="boxbox" value="&#x029C9;"/>
  <entity name="boxDL" value="&#x02557;"/>
  <entity name="boxDl" value="&#x02556;"/>
  <entity name="boxdL" value="&#x02555;"/>
  <entity name="boxdl" value="&#x02510;"/>
  <entity name="boxDR" value="&#x02554;"/>
  <entity name="boxDr" value="&#x02553;"/>
  <entity name="boxdR" value="&#x02552;"/>
  <entity name="boxdr" value="&#x0250C;"/>
  <entity name="boxH" value="&#x02550;"/>
  <entity name="boxh" value="&#x02500;"/>
  <entity name="boxHD" value="&#x02566;"/>
  <entity name="boxHd" value="&#x02564;"/>
  <entity name="boxhD" value="&#x02565;"/>
  <entity name="boxhd" value="&#x0252C;"/>
  <entity name="boxHU" value="&#x02569;"/>
  <entity name="boxHu" value="&#x02567;"/>
  <entity name="boxhU" value="&#x02568;"/>
  <entity name="boxhu" value="&#x02534;"/>
  <entity name="boxminus" value="&#x0229F;"/>
  <entity name="boxplus" value="&#x0229E;"/>
  <entity name="boxtimes" value="&#x022A0;"/>
  <entity name="boxUL" value="&#x0255D;"/>
  <entity name="boxUl" value="&#x0255C;"/>
  <entity name="boxuL" value="&#x0255B;"/>
  <entity name="boxul" value="&#x02518;"/>
  <entity name="boxUR" value="&#x0255A;"/>
  <entity name="boxUr" value="&#x02559;"/>
  <entity name="boxuR" value="&#x02558;"/>
  <entity name="boxur" value="&#x02514;"/>
  <entity name="boxV" value="&#x02551;"/>
  <entity name="boxv" value="&#x02502;"/>
  <entity name="boxVH" value="&#x0256C;"/>
  <entity name="boxVh" value="&#x0256B;"/>
  <entity name="boxvH" value="&#x0256A;"/>
  <entity name="boxvh" value="&#x0253C;"/>
  <entity name="boxVL" value="&#x02563;"/>
  <entity name="boxVl" value="&#x02562;"/>
  <entity name="boxvL" value="&#x02561;"/>
  <entity name="boxvl" value="&#x02524;"/>
  <entity name="boxVR" value="&#x02560;"/>
  <entity name="boxVr" value="&#x0255F;"/>
  <entity name="boxvR" value="&#x0255E;"/>
  <entity name="boxvr" value="&#x0251C;"/>
  <entity name="bprime" value="&#x02035;"/>
  <entity name="Breve" value="&#x002D8;"/>
  <entity name="breve" value="&#x002D8;"/>
  <entity name="brvbar" value="&#x000A6;"/>
  <entity name="Bscr" value="&#x0212C;"/>
  <entity name="bscr" value="&#x1D4B7;"/>
  <entity name="bsemi" value="&#x0204F;"/>
  <entity name="bsim" value="&#x0223D;"/>
  <entity name="bsime" value="&#x022CD;"/>
  <entity name="bsol" value="&#x0005C;"/>
  <entity name="bsolb" value="&#x029C5;"/>
  <entity name="bsolhsub" value="&#x0005C;&#x02282;"/>
  <entity name="bull" value="&#x02022;"/>
  <entity name="bullet" value="&#x02022;"/>
  <entity name="bump" value="&#x0224E;"/>
  <entity name="bumpE" value="&#x02AAE;"/>
  <entity name="bumpe" value="&#x0224F;"/>
  <entity name="Bumpeq" value="&#x0224E;"/>
  <entity name="bumpeq" value="&#x0224F;"/>
  <entity name="Cacute" value="&#x00106;"/>
  <entity name="cacute" value="&#x00107;"/>
  <entity name="Cap" value="&#x022D2;"/>
  <entity name="cap" value="&#x02229;"/>
  <entity name="capand" value="&#x02A44;"/>
  <entity name="capbrcup" value="&#x02A49;"/>
  <entity name="capcap" value="&#x02A4B;"/>
  <entity name="capcup" value="&#x02A47;"/>
  <entity name="capdot" value="&#x02A40;"/>
  <entity name="CapitalDifferentialD" value="&#x02145;"/>
  <entity name="caps" value="&#x02229;&#x0FE00;"/>
  <entity name="caret" value="&#x02041;"/>
  <entity name="caron" value="&#x002C7;"/>
  <entity name="Cayleys" value="&#x0212D;"/>
  <entity name="ccaps" value="&#x02A4D;"/>
  <entity name="Ccaron" value="&#x0010C;"/>
  <entity name="ccaron" value="&#x0010D;"/>
  <entity name="Ccedil" value="&#x000C7;"/>
  <entity name="ccedil" value="&#x000E7;"/>
  <entity name="Ccirc" value="&#x00108;"/>
  <entity name="ccirc" value="&#x00109;"/>
  <entity name="Cconint" value="&#x02230;"/>
  <entity name="ccups" value="&#x02A4C;"/>
